// <auto-generated />
using System;
using FluxMonitor.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FluxMonitor.Infrastructure.Migrations
{
    [DbContext(typeof(FluxMonitorDbContext))]
    [Migration("20260614135607_AddSystemSettings")]
    partial class AddSystemSettings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("FluxMonitor.Domain.Entities.SystemSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("CleanLogs")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CleanManifests")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ClientCompany")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<bool>("EnableGlobalErrorActions")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("LogsRetentionDays")
                        .HasColumnType("int");

                    b.Property<int>("ManifestsRetentionDays")
                        .HasColumnType("int");

                    b.Property<bool>("SendEmailOnFailure")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("TriggerWebhookOnFailure")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("SystemSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CleanLogs = true,
                            CleanManifests = false,
                            ClientCompany = "CustomCompany",
                            EnableGlobalErrorActions = true,
                            LogsRetentionDays = 3,
                            ManifestsRetentionDays = 90,
                            SendEmailOnFailure = true,
                            TriggerWebhookOnFailure = false
                        });
                });

            modelBuilder.Entity("FluxMonitor.Domain.Entities.Users", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UserGroup")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d"),
                            CreatedAt = new DateTime(2026, 6, 14, 13, 56, 6, 778, DateTimeKind.Utc).AddTicks(5540),
                            Email = "admin@fluxmonitor.com",
                            IsActive = true,
                            PasswordHash = "$2a$11$jyqaaIWQrM/BzcDHb3uq6efgLgEEQo7uOarDAiM9o.c.PAaFcCaCu",
                            UserGroup = "admin",
                            Username = "admin"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
