// <auto-generated />
using System;
using FluxMonitor.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FluxMonitor.Infrastructure.Migrations
{
    [DbContext(typeof(FluxMonitorDbContext))]
    [Migration("20260614214406_AddTelemetryAndAlertsTables")]
    partial class AddTelemetryAndAlertsTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("FluxMonitor.Domain.Entities.Alert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AlertType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("FlowName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<Guid>("ManifestId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("TriggeredAutomatedActions")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ManifestId");

                    b.ToTable("Alerts");
                });

            modelBuilder.Entity("FluxMonitor.Domain.Entities.Execution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<double>("DurationSeconds")
                        .HasColumnType("double");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("longtext");

                    b.Property<string>("FlowName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int?>("HttpRequestsReceivedCount")
                        .HasColumnType("int");

                    b.Property<int?>("HttpRequestsSentCount")
                        .HasColumnType("int");

                    b.Property<Guid>("ManifestId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ManifestName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int?>("ProcessedFilesCount")
                        .HasColumnType("int");

                    b.Property<int?>("ReceivedFilesCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("SystemType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ManifestId");

                    b.ToTable("Executions");
                });

            modelBuilder.Entity("FluxMonitor.Domain.Entities.Manifest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AlertChannels")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("AssociatedFlow")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("DirectoryIn")
                        .HasColumnType("longtext");

                    b.Property<string>("DirectoryOut")
                        .HasColumnType("longtext");

                    b.Property<string>("ExpectedFrequency")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FileClass")
                        .HasColumnType("longtext");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("MaxExecutionTime")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Recipients")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SchedulerMachine")
                        .HasColumnType("longtext");

                    b.Property<string>("SystemType")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Manifests");
                });

            modelBuilder.Entity("FluxMonitor.Domain.Entities.SystemSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("CleanLogs")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CleanManifests")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ClientCompany")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<bool>("EnableGlobalErrorActions")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("LogsRetentionDays")
                        .HasColumnType("int");

                    b.Property<int>("ManifestsRetentionDays")
                        .HasColumnType("int");

                    b.Property<bool>("SendEmailOnFailure")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("TriggerWebhookOnFailure")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("SystemSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CleanLogs = true,
                            CleanManifests = false,
                            ClientCompany = "CustomCompany",
                            EnableGlobalErrorActions = true,
                            LogsRetentionDays = 3,
                            ManifestsRetentionDays = 90,
                            SendEmailOnFailure = true,
                            TriggerWebhookOnFailure = false
                        });
                });

            modelBuilder.Entity("FluxMonitor.Domain.Entities.Users", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UserGroup")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d"),
                            CreatedAt = new DateTime(2026, 6, 14, 21, 44, 5, 180, DateTimeKind.Utc).AddTicks(3370),
                            Email = "admin@fluxmonitor.com",
                            IsActive = true,
                            PasswordHash = "$2a$11$5NeyS7YQ4MurvQyw0Tp/J.uGIl3NMdcQ1rVnyuLWllALnZPGtjloy",
                            UserGroup = "admin",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("FluxMonitor.Domain.Entities.Alert", b =>
                {
                    b.HasOne("FluxMonitor.Domain.Entities.Manifest", "Manifest")
                        .WithMany()
                        .HasForeignKey("ManifestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manifest");
                });

            modelBuilder.Entity("FluxMonitor.Domain.Entities.Execution", b =>
                {
                    b.HasOne("FluxMonitor.Domain.Entities.Manifest", "Manifest")
                        .WithMany()
                        .HasForeignKey("ManifestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manifest");
                });
#pragma warning restore 612, 618
        }
    }
}
